console.log("Rodando o Sistema de Informações de CS")
console.log("Como atualizar os arquivos")
console.log("Alterando outra mensaem")
console.log("Alterndo mais de um arquivo")
console.log("Criando outra mensagem para teste")
